[build]
  command = "pnpm run build"
  publish = "dist" # o la carpeta de tu build

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--version"      # evita que Netlify intente usar npm
  NETLIFY_USE_PNPM = "true"    # fuerza pnpm
