[build]
  command = "pnpm run build"
  publish = "dist" # o la carpeta de tu build

[build.environment]
  NODE_VERSION = "20"          # o el que uses realmente
  NPM_FLAGS = "--version"      # evita que Netlify intente usar npm
  NETLIFY_USE_PNPM = "true"    # fuerza pnpm
